service: meerkat
builder:
  arch: amd64
  driver: docker

image: ghcr.io/feather-page/cms
registry:
  server: ghcr.io
  username: shostakovich
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    PGGSSENCMODE: disable

servers:
  web:
    hosts:
      - 0.0.0.0
  job:
    hosts:
      - 0.0.0.0
    cmd: bundle exec rake solid_queue:start
