production:
  cleanup_images:
    class: CleanupOrphanedImagesJob
    schedule: every day at 3am
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
